export default {
  kind: 'collectionType',
  collectionName: 'articles',
  info: { singularName: 'article', pluralName: 'articles', displayName: 'Article' },
  options: { draftAndPublish: false },
  attributes: {
    title: { type: 'string', required: true },
    slug: { type: 'uid', targetField: 'title', required: true },
    excerpt: { type: 'text' },
    content: { type: 'json' },
    status: {
      type: 'enumeration',
      enum: ['draft', 'submitted', 'in_review', 'published', 'rejected'],
      default: 'draft',
      required: true,
    },
    featuredImage: { type: 'media', multiple: false, allowedTypes: ['images'] },
    tags: { type: 'json' },
    readTime: { type: 'integer', default: 0 },
    reviewNotes: { type: 'text' },
    views: { type: 'integer', default: 0 },
    likes: { type: 'integer', default: 0 },
    authorId: { type: 'integer', required: true },
    authorName: { type: 'string' },
    authorOccupation: { type: 'string' },
    authorAvatar: { type: 'string' },
    publishedAt: { type: 'datetime' },
    coverImageUrl: { type: 'string' },
  },
};
